### ISSUE TITLE
Return an error if buffer is full

### ISSUE THREAD

**Issue by troplin** [abonander/buf_redux#2]
`read_into_buf` should return an error if the buffer is full and no additional bytes are read.

**Comment by abonander** [comment]
I don't think this would help anyone. The buffer will return `Ok(0)` if the buffer is full, as this is the expected behavior of `Read::read()` when given a zero-length slice (though I have an early return in `Buffer::read_from()` because `hyper::server::Request` doesn't like zero-sized reads).
